export default [
{ value: "Acupuntura", label: "Acupuntura"},
{ value: "Anestesiologia", label: "Anestesiologia"},
{ value: "Angiologia", label: "Angiologia"},
{ value: "Cardiologia", label: "Cardiologia"},
{ value: "Cirurgia cardiovascular" , label: "Cirurgia cardiovascular" },
{ value: "Cirurgia da mão" , label: "Cirurgia da mão" },
{ value: "Cirurgia de cabeça e pescoço" , label: "Cirurgia de cabeça e pescoço" },
{ value: "Cirurgia do aparelho digestivo" , label: "Cirurgia do aparelho digestivo" },
{ value: "Cirurgia geral" , label: "Cirurgia geral" },
{ value: "Cirurgia oncológica" , label: "Cirurgia oncológica" },
{ value: "Cirurgia pediátrica" , label: "Cirurgia pediátrica" },
{ value: "Cirurgia plástica" , label: "Cirurgia plástica" },
{ value: "Cirurgia torácica" , label: "Cirurgia torácica" },
{ value: "Cirurgia vascular" , label: "Cirurgia vascular" },
{ value: "Clínica médica" , label: "Clínica médica" },
{ value: "Coloproctologia", label: "Coloproctologia"},
{ value: "Dermatologia", label: "Dermatologia"},
{ value:  "Endocrinologia" , label: "Endocrinologia" },
{ value: "Endoscopia", label: "Endoscopia"},
{ value: "Gastroenterologia", label: "Gastroenterologia"},
{ value: "Genética médica" , label: "Genética médica" },
{ value: "Geriatria", label: "Geriatria"},
{ value:  "Ginecologia e obstetrícia" , label: "Ginecologia e obstetrícia" },
{ value:  "Hematologia e hemoterapia" , label: "Hematologia e hemoterapia" },
{ value: "Homeopatia", label: "Homeopatia"},
{ value: "Infectologia", label: "Infectologia"},
{ value: "Mastologia", label: "Mastologia"},
{ value:  "Medicina de emergência" , label: "Medicina de emergência" },
{ value:  "Medicina de família"  , label: "Medicina de família"  },
{ value:  "Medicina do trabalho" , label: "Medicina do trabalho" },
{ value:  "Medicina  de tráfego" , label: "Medicina de tráfego" },
{ value: "Medicina esportiva" , label: "Medicina esportiva" },
{ value: "Medicina física"  , label: "Medicina física"  },
{ value: "Medicina intensiva" , label: "Medicina intensiva" },
{ value: "Medicina legal" , label: "Medicina legal" },
{ value: "Medicina nuclear" , label: "Medicina nuclear" },
{ value: "Medicina social" , label: "Medicina social" },
{ value: "Nefrologia", label: "Nefrologia"},
{ value: "Neurocirurgia", label: "Neurocirurgia"},
{ value: "Nutrologia", label: "Nutrologia"},
{ value: "Oftalmologia", label: "Oftalmologia"},
{ value:  "Oncologia clínica", label: "Oncologia clínica"},
{ value: "Ortopedia", label: "Ortopedia"},
{ value: "Otorrinolaringologia", label: "Otorrinolaringologia"},
{ value: "Patologia", label: "Patologia"},
{ value: "Medicina laboratorial" , label: "Medicina laboratorial" },
{ value: "Pediatria", label: "Pediatria"},
{ value: "Pneumologia", label: "Pneumologia"},
{ value: "Psiquiatria", label: "Psiquiatria"},
{ value: "Radiologia", label: "Radiologia"},
{ value: "Radioterapia", label: "Radioterapia"},
{ value: "Reumatologia", label: "Reumatologia"},
{ value: "Urologia", label: "Urologia"},
]